### ISSUE TITLE
canot open your code file 

### ISSUE THREAD

**Issue by juseph-dan** [Delphi89/Hyperspectral-Images-Classification-in-Pytorch-with-Multiple-GPUs#1]
could be damaged, can you help

**Comment by Delphi89** [comment]
I've tried to update the file, please check again.
If not working, let me know and I'll try to create a ticket. Meanwhile, if you send an email address, I can send the code to you.

**Comment by juseph-dan** [comment]
still the same error could not be loaded,<mehdihym@gmail.com>, Thanks a lot, appreciate

**Comment by Delphi89** [comment]
I found that if you click on "< >" button or "Raw" button after having the error, you can see the code.

**Comment by Delphi89** [comment]
I've changed the extension to .py (python) instead of .ipynb (jupyter notebook) and now the file is readable.
