### ISSUE TITLE
pavia dataset 

### ISSUE THREAD

**Issue by belovedj** [Delphi89/Hyperspectral-Images-Classification-in-Pytorch-with-Multiple-GPUs#2]
Your code file cannot be opened, but I would like to see how your pavia dataset is used. The version of matlab I downloaded is not available to me. Could you please send your code file again？thank you.

**Comment by Delphi89** [comment]
I've tried to update the file, please check again. 
If not working, let me know and I'll try to create a ticket. Meanwhile, if you send an email address, I can send the code to you.

**Comment by Delphi89** [comment]
I found that if you click on "< >" button or "Raw" button after having the error, you can see the code.

**Comment by Delphi89** [comment]
I've changed the extension to .py (python) instead of .ipynb (jupyter notebook) and now the file is readable.
