### ISSUE TITLE
The problems of DB.m

### ISSUE THREAD

**Issue by whwczxm** [Delphi89/Hyperspectral-Images-Classification-in-Pytorch-with-Multiple-GPUs#4]
Thanks for your great job!
But I have some questions of DB.m
The input of DB.m are Pavia_db.* files, like the Pavia_db.test_target, how you define the "test_target"? Or how you convert the PaviaU.mat (and the gt file) to this pavia_db?
And the output of DB.m are test_*_20p.mat files, however the input of the train code actually uses "database200.mat", it seems like their assembling progress is missing.

**Comment by Delphi89** [comment]
Hi,

Thank you for your comment.
The file is not correct. I'm working to update the file and publish with more comments.
Hope to complete it in the next hours.

Thank you,
Paul

**Comment by Delphi89** [comment]
Description of the Matlab code:
1. original Pavia University database loaded from disk...
2. 2x zero padding added to database (to allow finding neighbours for the pixels from the matrix margins)...
3. test_data vector and test_target vector created using 24 neighbours...
4. train_data and train_target created using 24 neighbours...
5. new/clean database saved.

The new code was uploaded in github in the main branch in BD.m file.
Please let me know if the above summary or the code are not clear or you have more questions.
